# Generated by Django 3.2.11 on 2022-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220505_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, default='Tunis', max_length=50, null=True),
        ),
    ]
