# Generated by Django 3.2.11 on 2022-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patient_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='status', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
