# Generated by Django 3.2.11 on 2022-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='covid19',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='normal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pneumonia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='tuberculosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
