# Generated by Django 3.2.11 on 2022-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220506_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='comment',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='covid19',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='model_feedback',
            field=models.CharField(choices=[('covid19', 'covid19'), ('normal', 'normal'), ('pneumonia', 'pneumonia'), ('tuberculosis', 'tuberculosis')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='normal',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pneumonia',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='tuberculosis',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
