# Generated by Django 3.2.11 on 2022-05-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_prediction_dominant_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
