# Generated by Django 3.2.11 on 2022-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220506_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='heatmap',
            field=models.ImageField(blank=True, upload_to='heatmap'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='raw'),
        ),
    ]
